export const ACTION_TYPES = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
	SET_PRODUCT_TO_BASKET: 'SET_PRODUCT_TO_BASKET',
	ADD_PRODUCT_TO_BASKET: 'ADD_PRODUCT_TO_BASKET',
	REMOVE_PRODUCT_FROM_BASKET: 'REMOVE_PRODUCT_FROM_BASKET',
	RESET_BASKET: 'RESET_BASKET',
	INCREASE_PRODUCT_COUNT_BASKET: 'INCREASE_PRODUCT_COUNT_BASKET',
	DECREASE_PRODUCT_COUNT_BASKET: 'DECREASE_PRODUCT_COUNT_BASKET',
};
